### ISSUE TITLE
Bullet chart problem

### ISSUE THREAD

**Issue by ahumke** [okviz/BulletChart#23]
In my bullet chart I want the metric to display the value for only the most recent year.  I've added a filter for the year portion of my date field in the visual filter area but the bullet charts is not recognizing it.  Instead it is returning the average across all years.  I have no issues with getting the date to filter in a table.

**Comment by danieleperilli** [comment]
It seems a DAX issue... Please, provide a report to reproduce the issue.

**Comment by ahumke** [comment]
How do I provide the report?  Is there a simple way to export the dax measures in addition to the table?

**Comment by danieleperilli** [comment]
Attach the report here or send it to support@okviz.com

**Comment by ahumke** [comment]
I have live ODS connection to bring in the data.  I don't think the power bi file will help you.  What are you referring to by "report"

**Comment by danieleperilli** [comment]
We need to reproduce the issue to understand it. So, please create a sample report file (PBIX) with dummy data.

**Comment by ahumke** [comment]
Here are the sample files to illustrate the issue I’m having with the year filter not impacting the bullet chart.

Thanks,
Amy

Amy M. Humke, Ph.D.
Director of Institutional Research
P: (815) 479-7518 l F: (815) 455-9871
ahumke@mchenry.edu<mailto:ahumke@mchenry.edu>
..............................................
8900 U.S. Highway 14
Crystal Lake, IL 60012
..............................................
www.mchenry.edu<http://www.mchenry.edu>

[Description: cid:image003.jpg@01CD86D4.7E60E340]

**Comment by danieleperilli** [comment]
You missed the attachment. Don't reply to GitHub notification with attachments.

**Comment by ahumke** [comment]
[Trouble Shoot Bullet Year Filter.zip](https://github.com/okviz/BulletChart/files/2346202/Trouble.Shoot.Bullet.Year.Filter.zip)

**Comment by danieleperilli** [comment]
You are using the Bullet Chart from Microsoft, not the Bullet Chart by OKViz.

**Comment by ahumke** [comment]
[Trouble Shoot Bullet Year Filter.zip](https://github.com/okviz/BulletChart/files/2346222/Trouble.Shoot.Bullet.Year.Filter.zip)

**Comment by ahumke** [comment]
When I change it to OkViz it does the same thing.  Neither register the filtered date for some reason.  But the table will.

**Comment by danieleperilli** [comment]
Different visuals have different code, so your issue is not related to the visual. There is something strange in your measures, I guess. 
I suggest you to isolate the issue (have you try to change the bullet with a table?), and to ask for support on a DAX specialized forum or on our SQLBI website. Sorry, this space is only for bugs in our visuals.

**Comment by marcosqlbi** [comment]
The issue is that the behavior is the same in the Microsoft visual - which means that it is Power BI sending the bad data to the visual. Thus, we cannot do much to fix it in OKViz, I suggest you opening a support incident with Microsoft showing the issue with their visual - any workaround or fix will work with the visual from OKViz, too.
